-- AlterTable
ALTER TABLE "Car" ADD COLUMN     "vsStarCountMax" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "stLoseBits" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "CarSettings" ALTER COLUMN "volume" SET DEFAULT 2;
